spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/decornext
spring.datasource.username=postgres
spring.datasource.password=@subham2120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
razorpay.key.id=rzp_test_TezL8hWItrvPsn
razorpay.key.secret=7mpB0XlWG5nZCzSo6IdRU5oC

jwt.secret=DecorNextSuperSecretKeyForJwtAuthentication2026
jwt.expiration=3600000